###
GET http://localhost:3000/post
###
GET http://localhost:3000/post?sender=asafi
###
GET http://localhost:3000/post/65080d84ca16c0f1f1ba116c
###
POST http://localhost:3000/post
Content-Type: application/json

{
  "message": "new message",
  "sender": "asaf"
}
###
PUT http://localhost:3000/post/65119ce02e12fc0374b5708f
Content-Type: application/json

{
  "_id": "65119ce02e12fc0374b5708f",
  "message": "brand new message",
  "sender": "new sender"
}
###